# This has been created by @lillieH1000

name: Build the iSponsorBlock Deb

on:
  workflow_dispatch:
    
jobs:
  build:
    name: iSponsorBlock
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main

      - name: Checkout RootHide/theos
        uses: actions/checkout@main
        with:
          repository: RootHide/theos
          ref: master
          submodules: recursive
          path: theos

      - name: Checkout chrisharper22/sdks
        uses: actions/checkout@main
        with:
          repository: chrisharper22/sdks
          ref: main
          sparse-checkout: iPhoneOS16.2.sdk
          path: theos/sdks

      - name: Checkout PoomSmart/YouTubeHeader
        uses: actions/checkout@main
        with:
          repository: PoomSmart/YouTubeHeader
          ref: main
          path: YouTubeHeader

      - name: Build Package 
        id: build_package
        run: |
          brew install make xz ldid 
          export THEOS=theos
          gmake clean package FINALPACKAGE=1
          PACKAGE_VERSION=$(grep '^PACKAGE_VERSION' Makefile | cut -d' ' -f3)
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_OUTPUT
          echo "==> Built v$PACKAGE_VERSION Successfully."

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          path: packages/*.deb
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT: ${{ inputs.create_release }}
        with:
          tag_name: v${{ steps.build_package.outputs.PACKAGE_VERSION }}
          name: v${{ steps.build_package.outputs.PACKAGE_VERSION }}
          files: packages/*.deb
          draft: ${{ env.DRAFT }}
